steps:
# 1. Build the Docker container image for the CCP
- name: 'gcr.io/cloud-builders/docker'
  id: Build-CCP-Image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
  - '.' # Use the root directory as the build context
  - '-f' # Specify the Dockerfile location within the context
  - 'ccp/Dockerfile'
  
# 2. Deploy the new container image to Google Cloud Run
# --- FIX ---
# Updated the builder image from the deprecated 'gcr.io/google.com/cloudsdk/cloud-sdk'
# to the new standard 'gcr.io/cloud-builders/gcloud'
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy-to-CloudRun
  args:
  - 'gcloud'
  - 'run'
  - 'deploy'
  - 'lulimi-ccp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
  - '--region'
  - 'africa-south1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  
# Fix for the persistent "logging" error and explicit Service Account
options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 457527257985@cloudbuild.gserviceaccount.com

images:
- 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
