# This pipeline deploys the NEW Lulimi Translator app.
# It re-uses all the permissions and logic from our successful CCP deployment.

steps:
# 1. Build the new translator image
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Translator-Image
  args:
  - 'build'
  - '-t'
  # Note: Pushing to a new image name: 'lulimi-translator'
  - 'africa-south1-docker.pkg.dev/$PROJECT_ID/lulimi-repo/lulimi-translator:$COMMIT_SHA'
  - '.' # Build context is the root
  - '-f' # Specify the new Dockerfile
  - 'translator/Dockerfile'

# 2. Grant all necessary permissions (this is our proven, robust fix)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Grant-All-Permissions
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Grant Artifact Registry Writer (to push)
    gcloud projects add-iam-policy-binding lulimi-ccp-project --member="serviceAccount:457527257985-compute@developer.gserviceaccount.com" --role="roles/artifactregistry.writer"
    # Grant Cloud Run Admin (to deploy)
    gcloud projects add-iam-policy-binding lulimi-ccp-project --member="serviceAccount:457527257985-compute@developer.gserviceaccount.com" --role="roles/run.admin"
    # Grant Service Account User (to set identity)
    gcloud projects add-iam-policy-binding lulimi-ccp-project --member="serviceAccount:457527257985-compute@developer.gserviceaccount.com" --role="roles/iam.serviceAccountUser"
    echo "All 3 permissions granted."

# 3. Wait 3 minutes for IAM permissions to propagate (our proven fix)
- name: 'ubuntu'
  id: Wait-for-IAM-Propagation
  args: ['sleep', '180']

# 4. Explicitly Push the image (this was a key fix)
- name: 'gcr.io/cloud-builders/docker'
  id: Push-Image
  args:
  - 'push'
  - 'africa-south1-docker.pkg.dev/$PROJECT_ID/lulimi-repo/lulimi-translator:$COMMIT_SHA'

# 5. Deploy the new service
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy-Service
  args:
  - 'run'
  - 'deploy'
  # Note: New service name 'lulimi-translator'
  - 'lulimi-translator'
  - '--image'
  - 'africa-south1-docker.pkg.dev/$PROJECT_ID/lulimi-repo/lulimi-translator:$COMMIT_SHA'
  - '--region'
  - 'africa-south1'
  - '--platform'
  - 'managed'
  - '--project'
  - 'lulimi-ccp-project'
  - '--service-account'
  - '457527257985-compute@developer.gserviceaccount.com'
  - '--verbosity'
  - 'debug'

# 6. Make the new service public
- name: 'gcr.io/cloud-builders/gcloud'
  id: Make-Service-Public
  args:
  - 'run'
  - 'services'
  - 'add-iam-policy-binding'
  - 'lulimi-translator' # The new service name
  - '--region'
  - 'africa-south1'
  - '--platform'
  - 'managed'
  - '--project'
  - 'lulimi-ccp-project'
  - '--member=allUsers'
  - '--role=roles/run.invoker'

# Tell Cloud Build the final image name
images:
- 'africa-south1-docker.pkg.dev/$PROJECT_ID/lulimi-repo/lulimi-translator:$COMMIT_SHA'

# Set the logging fix
options:
  logging: CLOUD_LOGGING_ONLY

# Use the correct service account to run the build
serviceAccount: 457527257985-compute@developer.gserviceaccount.com
