steps:
# 1. Build the Docker container image for the CCP
- name: 'gcr.io/cloud-builders/docker'
  id: Build-CCP-Image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
  - '.'
  - '-f'
  - 'ccp/Dockerfile'
  
# 2. Deploy the new container image to Google Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  id: Deploy-to-CloudRun
  args:
  - 'gcloud'
  - 'run'
  - 'deploy'
  - 'lulimi-ccp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
  - '--region'
  - 'africa-south1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  
options:
  # FIX: Resolves the persistent error about logging requirements
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 457527257985@cloudbuild.gserviceaccount.com

images:
- 'gcr.io/$PROJECT_ID/lulimi-ccp:$COMMIT_SHA'
